name: Graal Native Image 
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Maven Graal Native Image creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.2.0.java8'
      - name: Generate Graal Native Image
        run: java -version && gu list && gu install native-image && mvn -B clean package -Pgraal && ls -rtla
      - run: mkdir staging && cp target/com*application staging && ls -lrta staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
  
