name: Graal Native Image 
on:
  release:
    types: [created]
jobs:
  build:
    name: Maven Graal Native Image creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.2.0.java8'
      - name: Generate Graal Native Image
        run: java -version && gu list && gu install native-image && mvn -B clean package -Pgraal
      - name: upload native image package on release
      - run: ls -lrta && mkdir staging && cp target/com*application staging && ls -lrta staging && ./staging/com*
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
