name: Graal Native Image 
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Maven Graal Native Image creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '20.0.0.java11'
      - name: Generate Graal Native Image
        run: java -version && gu list && gu install native-image && mvn -B clean package -Pgraal && ./com.aiocdawacs.smart.pharmacy.smartpharmacyproductserviceapplication
        
      - name: Create tarball
        run: tar -zcvf "awacs-ubuntu-latest.tar.gz" com.aiocdawacs.smart.pharmacy.smartpharmacyproductserviceapplication
        run: ls -lrta
        